CotripperPlatform/CoTrip

.editorconfig
browser/package-lock.json

Created editorconfig file in root of directory. Added rules to handle JS syntax and python syntax, as well as markdown. I'm not totally positive but everyone on the project may need to have the vscode editorconfig extension installed? I'll look into this.

Created editorconfig

---

client/src/App.js
client/src/index.js

#27 I added react router to index.js and a sample route and link to app.js.

React Router setup PR

---

client/src/App.css

Per issue #147, Green has been added as a CSS variable.

Added green as a vabiable PR

---

client/src/App.css

Added some bolds weights to Open Sans font.

Added other weights to Open Sans PR

---

client/src/components/Logo/Logo.css
client/src/components/Logo/Logo.js

Updated the logo css names to follow new convention

Logo PR update css names

---

client/src/components/CommentBody/CommentBody.css
client/src/components/CommentBody/CommentBody.js
client/src/components/InputTextField/InputTextField.css
client/src/components/InputTextField/InputTextField.js
client/src/components/PostBody/PostBody.css
client/src/components/PostBody/PostBody.js

updated these. Does this look right?

PR Css name fix

---

client/src/App.css

@DallasLind Pointed out that the Person Card has a border color that was missing from the CSS variables. This has been added in.

Added a slightly darker shade of yellow to the CSS variables PR

---

client/src/components/Button/Button.css
client/src/components/Button/Button.js

I update CSS with block-element-modifier.

Button CSS w/ block-element-modifier PR

---

client/src/components/Button/Button.css
client/src/components/Button/Button.js
client/src/components/Button/Button.stories.js

I added like and comment buttons for new issue #179. 
I set a min-width for the buttons but set their width to generally be 50% of the container because I want their width to expand to fill half of the post container. Does that seem right?

Component button: Like and Comment Buttons PR

---

client/src/App.css

Per issue #183, new variables were created to cover colors for hovers as well as a gradient used for several backgrounds.

Added hover color variables as well as one for a yellow/white gradient

---

client/src/components/Card/Card.css
client/src/components/Card/Card.js

#146 I moved the image from an img tag to a background image of the wrapping div. This will make it easier to style child components.

Component: Card PR

---

client/src/components/PostBody/PostBody.js

Added key to map in PostBody component

add key to map - hot fix

---

client/src/components/InputTextField/InputTextField.css

Had to fix widths for forms, they were blowing out of divs when used in other components.

Component: Input text field, PR plz pull me fast

---

client/src/components/NavLink/NavLink.css

fixed margin for bill's navbar

merge hotfix-navlink into develop

---

client/src/components/Card/Card.css
client/src/components/Card/Card.js
client/src/components/Card/Card.stories.js

I realized we were missing this version of the card component from the mock-up so I put it together really quick. Let me know if you guys see anything that could be changed. To render this version of the card you pass in a prop of ```discover={true}```

Component: Card,  Update PR

---

client/.storybook/addons.js
client/.storybook/config.js
client/package.json

added 4 breakpoints to storybook =)

merge hotfix-storybook-responsive-setup into develop

---

api/Pipfile
api/Pipfile.lock
api/api/settings.py
api/cotrip_app/admin.py
api/cotrip_app/apps.py
api/cotrip_app/models.py
api/cotrip_app/tests.py
api/cotrip_app/views.py
api/settings.sql

#252 Ran the command startapp command and created a new app folder called cotrip_app. Connected the folder to the project.

Created and set up the CoTrip app in Django

---

client/src/components/CarouselDots/CarouselDots.stories.js
client/src/components/OnboardingParent/OnboardingParent.css
client/src/components/OnboardingParent/OnboardingParent.js
client/src/components/OnboardingParent/OnboardingParent.stories.js
client/src/components/OnboardingParent/OnboardingParent.test.js

Setup parent Onboarding component to act as a template for Onboarding children components.
#216

PR: Parent Onboarding Component

---

client/src/components/TripCard/TripCard.stories.js

merge 'hotfix-image-paths' into 'develop'

---

client/src/components/GroupCard/GroupCard.css

I updated the sizing of the card to use rem instead of px or %.

Component: Group Card Responsiveness PR

---

api/Pipfile
api/Pipfile.lock
api/accounts/admin.py
api/accounts/apps.py
api/accounts/models.py
api/accounts/serializers.py
api/accounts/tests.py
api/accounts/urls.py
api/accounts/views.py
api/api/settings.py
api/api/urls.py

Want to merge api-accounts with backend branch

add accounts app with user signup and login

---

client/src/components/UpcomingEventsCard/UpcomingEventsCard.css

I updated the sizing of the card to use rem instead of px or %.

Component: Upcoming Events Card Responsiveness PR

---

client/src/components/NavLink/NavLink.css

merge 'hotfix-navlink' into 'develop'

---

client/jsconfig.json
client/src/App.js
client/src/pages/SplashPage/SplashPage.js

added jsconfig.json:
{
"compilerOptions": {
"baseUrl": "src"
},
"include": ["src"]
}
tested relative import ✅

merge 'relative-import-paths-setup' into 'develop'

---

client/src/components/Logo/Logo.test.js

Logo Test Pull Request

---

client/src/components/ForumPost/ForumPost.test.js

ForumPost Component PR

---

client/src/components/ExtraUsers/ExtraUsers.test.js

Extra Users Component PR

---

client/src/components/PreviousTripsCard/PreviousTripsCard.js
client/src/components/PreviousTripsCard/PreviousTripsCard.test.js

Previous Trip Card Test PR

---

client/src/components/TripDetails/TripDetails.test.js

TripDetails Test PR

---

client/src/components/TripCard/TripCard.test.js

TripCard Tests PR

---

client/src/components/NavLink/NavLink.js
client/src/components/NavLink/NavLink.test.js

Added navlink test from issue #232

Navlink Test PR

---

client/src/components/CommentBody/CommentBody.js
client/src/components/CommentBody/CommentBody.test.js

add test for comment body issue #224

Comment Body Test PR

---

client/src/components/MediaCard/MediaCard.test.js

Added tests for media card issue #230

MediaCard Test PR

---

client/src/components/InputTextField/InputTextField.js
client/src/components/InputTextField/InputTextField.test.js

I added tests for this component #228

InputTextField Test PR

---

client/src/components/Footer/Footer.test.js

I added tests for the footer component #225

Footer Test PR

---

client/src/components/BookTripCard/BookTripCard.js
client/src/components/BookTripCard/BookTripCard.stories.js

Hotfix book

---

client/src/components/BookTripCard/BookTripCard.test.js

Book Trip Test PR

---

client/src/components/TrendingHashtagCard/TrendingHashtagCard.js
client/src/components/TrendingHashtagCard/TrendingHashtagCard.test.js

Trending Hashtag Test PR

---

client/src/components/BookATripImage/BookATripImage.css
client/src/components/BookATripImage/BookATripImage.js
client/src/components/BookATripImage/BookATripImage.stories.js
client/src/components/BookATripImage/BookATripImage.test.js

Component: Book A Trip Page Image PR

---

api/Pipfile
api/Pipfile.lock
api/accounts/admin.py
api/accounts/apps.py
api/accounts/models.py
api/accounts/serializers.py
api/accounts/tests.py
api/accounts/urls.py
api/accounts/views.py
api/api/settings.py
api/api/urls.py

I created an accounts app for the backend with user signup and login like we did for the books api. 
How does this look?

Add accounts app, user signup and login PR

---

client/src/index.css

Added box-sizing: border-box to index.css file.

hotfix - index.css

---

client/src/components/Logo/Logo.js

Per Bill's request, I wrapped the logo links around the div for the nav bar.

Logo link hot fix

---

client/src/App.js
client/src/pages/ComingSoonPage/ComingSoonPage.css
client/src/pages/ComingSoonPage/ComingSoonPage.js
client/src/pages/ComingSoonPage/ComingSoonPage.stories.js
client/src/pages/ComingSoonPage/ComingSoonPage.test.js

I made a page that just displays the CoTripper yellow and the words "Coming Soon". I made this for all the buttons on pages that don't lead anywhere, I figured we could have them link to this page instead of nothing. Totally up to you guys if you want to include this, I just thought it might be cool!

Component/Page: Coming Soon PR

---

client/src/components/Navbar/Navbar.css

Removed the z-index for now since it's not behaving properly with the banner images.

Adjusting css to remove z-index for now since it's not behaving properly - Hofix

---

client/src/components/BookATripImage/BookATripImage.js
client/src/components/BookATripImage/BookATripImage.test.js

Book a trip image test PR

---

client/src/components/Navbar/Navbar.css

This should take care of the problem in issue #397. I removed the position tag from the burger icon.

This should fix the issue with the burger icon sticking - PR

---

api/api/settings.py

- Description of changes made: STATIC_URL

backend code snippet test

---

api/api/settings.py
api/forum/admin.py
api/forum/apps.py
api/forum/models.py
api/forum/tests.py
api/forum/views.py

created django app for forum

---

client/src/components/TrendingHashtagCard/TrendingHashtagCard.css

#398 
Changed container and font-size metrics to be more responsive.
yes
none
no

Updating Hashtag Text responsiveness

---

client/src/components/PersonCardDiscover/PersonCardDiscover.css
client/src/components/PersonCardDiscover/PersonCardDiscover.js
client/src/components/PersonCardDiscover/PersonCardDiscover.stories.js
client/src/components/PersonCardDiscover/PersonCardDiscover.test.js

- Related Issue (include '#'): Issue #324 
- Description of changes made: Created the "Discover New Connections" component.
- Is the feature complete/bug resolved/etc..: Feature completed.
- Any known bugs/strange behavior: No known bugs/issues.

Component discover connections

---

api/accounts/fixtures-accounts.json
api/trip/fixtures-trip.json

- Related Issue (include '#'): #526 
- Description of changes made: Added fixtures for the Trip app, including multiple Locations, Trips, and Activities
- Is the feature complete/bug resolved/etc..: Yes
- Any known bugs/strange behavior: Not so far.
These should all work with the accounts and groups models.

Trip Fixtures - Resolves #526

---

api/api/settings.py
client/src/App.js

- Description of changes made: Only Syntax change
- Any known bugs/strange behavior: No

small change to the Services folder

---

README.md
api/README.md
client/README.md

- Description of changes made: Updated all Readme's to include the deployed links.

Updated all Readme's to include Deployed Links

---

api/README.md

retry on updated readme

---

client/src/App.js
client/src/components/NavLink/NavLink.js
client/src/components/Navbar/Navbar.js
client/src/pages/CommunityPage/CommunityPagePeople.css
client/src/pages/CommunityPage/CommunityPagePeople.js

- Related Issue (include '#'): #555 
- Description of changes made: I created this page! It's all static right now -- doesn't render live data just yet. 
- Is the feature complete/bug resolved/etc..: Until the back end is integrated with the front end, yes.
- Any known bugs/strange behavior: None to my knowledge.

Community people page

---

client/src/components/Banner/Banner.css
client/src/components/Card/Card.css
client/src/components/GroupsList/GroupsList.css
client/src/components/Modal/Modal.css
client/src/components/OnboardingPills/OnboardingPills.css
client/src/components/PreviousTripsCard/PreviousTripsCard.css
client/src/components/PreviousTripsCard/PreviousTripsCard.js
client/src/components/TripCard-Users/TripCard-Users.css
client/src/components/TripCard-Users/TripCard-Users.js
client/src/pages/MemberProfilePage/MemberProfilePage.css
client/src/pages/MemberProfilePage/MemberProfilePage.js
client/src/pages/OnboardingPage/OnboardingPage.css
client/src/pages/OnboardingPage/PersonalSettingsForm/PersonalSettingsForm.js
client/src/pages/OnboardingPage/UserSetupForm/UserSetupForm.css
client/src/pages/OnboardingPage/UserSetupForm/UserSetupForm.js

#595, #610
Created Password requirements box and re-styled the text input fields SITE WIDE to have correct padding. Resolved issue with Modal behind images on Forum page.
Yes.
No.

Added password requirements, styled input boxes sitewide, fixed modal overlay issue.

---

client/package-lock.json
client/package.json
client/src/pages/ForumPage/ForumPage.css
client/src/pages/ForumPage/ForumPage.js
client/src/pages/ForumPage/ForumPageDiscover.js
package-lock.json

#617 
added some media query to make the the forum page and forum discover page responsive on iphone X
yes
not at the moment 

Forum page responsive feature branch

---

api/accounts/views.py
client/src/App.js
client/src/components/Bio/Bio.js
client/src/components/Icon/Icon.js
client/src/components/InputTextField/InputTextField.js
client/src/pages/MemberProfilePage/MemberProfilePage.js
client/src/pages/OnboardingPage/UserSetupForm/UserSetupForm.css

#619 
`/member-page` now dynamically loads your profile data and allows you to update your first name, last name, and bio in-place.
Still needed: profile image replacement, age, interests (pills from onboarding).

Dynamic user profile

---

api/api/CoTripper.postman_collectionPROFILEandPOST.json
api/api/CoTripper.postman_environmentPROFILEandPOST.json

#621 
Exported the Postman.json files and placed them in the API directory.  The files contain all the information needed to test routes for Post and Profile in Postman.
Yes.
No.
None.

added postman collections and env variable files to api dir

---

client/src/App.js
client/src/pages/ForumPage/ForumPage.css
client/src/pages/ForumPage/ForumPageHashtagTopic.js

- Related Issue (include '#'): I fixed the styling and follow button so it functions on topic page.

Scott fix topic

---

client/src/App.js

fixed app.js
